### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by tebriz159** [theriley106/Nightchord#2]
Hello, I want to contribute in your new project and I made a logo for the project. If you like it I'll send you all files. I'll wait for your answer )

![01](https://user-images.githubusercontent.com/31902754/39545720-ed45a34a-4e06-11e8-879a-389accd28f23.png)

**Comment by theriley106** [comment]
@tebriz159 This is AMAZING.  That would be so awesome if you could me the files! I'll make it the official logo for the project!  My email is christopherlambert106@gmail.com

Best,
Chris

**Comment by tebriz159** [comment]
I've send them all
